<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ad extends Model
{

    protected $table = 'real_estate_ads';
    public $timestamps = true;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'geo_bln',
        'geo_land',
        'obj_regio1',
        'obj_regio2',
        'obj_regio3',
        'obj_zipCode',
        'geo_krs',
        'geo_plz',
        'obj_street',
        'obj_streetPlain',
        'obj_houseNumber',
        'obj_serviceCharge',
        'obj_typeOfFlat',
        'obj_courtage',
        'obj_floor',
        'obj_immotype',
        'obj_ityp',
        'obj_heatingType',
        'obj_plotAreaRange',
        'obj_usableArea',
        'obj_lotArea',
        'obj_cId',
        'obj_project_id',
        'obj_scoutId',
        'obj_cwId',
        'obj_objectnumber',
        'obj_newlyConst',
        'obj_balcony',
        'obj_hasKitchen',
        'obj_lift',
        'obj_garden',
        'obj_picture',
        'obj_picturecount',
        'beschreibung',
        'obj_noRooms',
        'obj_noRoomsRange',
        'obj_livingSpace',
        'obj_parkingSpace',
        'obj_numberOfFloors',
        'obj_constructionPhase',
        'obj_rented',
        'obj_livingSpaceRange',
        'obj_barrierFree',
        'obj_yearConstructedRange',
        'obj_yearConstructed',
        'obj_interiorQual',
        'obj_condition',
        'obj_lastRefurbish',
        'obj_buildingType',
        'obj_totalRent',
        'obj_baseRent',
        'obj_heatingCosts',
        'obj_baseRentRange',
        'obj_rentSubsidy',
        'obj_pricetrend',
        'obj_pricetrendrent',
        'obj_purchasePriceRange',
        'obj_purchasePrice',
        'obj_pricetrendbuy',
        'obj_firingTypes',
        'obj_thermalChar',
        'obj_energyEfficiencyClass',
        'obj_energyType',
        'obj_international',
        'obj_noParkSpaces',
        'obj_ExclusiveExpose',
        'obj_telekomTvOffer',
        'obj_telekomInternetType',
        'obj_telekomUploadSpeed',
        'obj_telekomHdTelephone',
        'obj_telekomDownloadSpeed',
        'obj_telekomHybridUploadSpeed',
        'obj_telekomInternetProductName',
        'obj_telekomHybridDownloadSpeed',
        'obj_telekomInternetProductAvailable',
        'obj_telekomInternetServices',
        'obj_telekomInternetUrlMobile',
        'obj_telekomInternet',
        'obj_telekomInternetUrl',
        'obj_telekomInternetTechnology',
        'obj_telekomTrackingGroup',
        'obj_cellar',
        'obj_petsAllowed',
        'ga_cd_cxp_historicallisting',
        'ga_cd_customer_group',
        'ga_cd_maillead_default_shown',
        'ga_cd_developer_virtualreality',
        'ga_cd_application_requirements',
        'ga_cd_via_qualified',
        'ga_cd_via',
        'evt_count_pm_sig',
        'obj_depositLink',
        'obj_assistedLiving',
        'obj_groupnumber',
        'obj_galleryAd',
        'URL',
        'obj_nbp',
        'expose_title',
        'expose_address_block',
        'expose_guests_toilet',
        'expose_granny_flat',
        'expose_bedrooms',
        'expose_bathrooms',
        'expose_vacant_from',
        'expose_realtor_commission_percentage',
        'expose_monument_protection',
        'expose_energy_certificate',
        'expose_property_description',
        'expose_property_equipment',
        'expose_location_text',
        'expose_misc_text'
    ];

    protected $primaryKey = 'obj_scoutId';
}